name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
       DOCKER_USER: ${{secrets.DOCKER_USER}}
       DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lion2486/frontend-nginx:latest
    - name: Docker Push
      run: docker push lion2486/frontend-nginx:latest
